version: '1'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - 27017:27017
  web-app:
    container_name: web-app
    build: ./web-app
    environment: 
      - MONGODB_CONNSTRING=mongodb://admin:admin123@mongodb
    ports:
      - 5001:5001
    depends_on:
      - mongodb
  machine-learning:
    container_name: ml-client
    build: ./machine-learning-client
    environment: 
      - MONGODB_CONNSTRING=mongodb://admin:admin123@mongodb
    ports:
      - 8080:8080
    depends_on:
      - mongodb